### ISSUE TITLE
模型数据缺失问题

### ISSUE THREAD

**Issue by relaxxx2018** [Liang-NTU/ReMVC#1]
您好，老师。关于remvc_data代码中用到./clear_data/r_dict.pickle数据方便提供一下吗？或者具体数据格式。谢谢您了。

**Comment by Liang-NTU** [comment]
之前就提交了，在clear_data文件夹下，你可以下载

**Comment by relaxxx2018** [comment]
不好意思描述错了，是缺少./clear_data/region_dict.pickle文件，该目录下只有r_dict.pickle，r_dict.pickle数据中缺少关于region_dict[idx]["poi"]属性。

**Comment by Liang-NTU** [comment]
不好意思，我查查看，如果缺失了，会上传的，谢谢

**Comment by Liang-NTU** [comment]
应该是缺少了training_dict.pickle，应该是因为文件大于25mb，没上传成功，我之后重新update一下，谢谢你的问题

**Comment by lizc-sdu** [comment]
老师您好，training_dict.pickle这个数据方便提供一下吗，非常感谢！

**Comment by Liang-NTU** [comment]
https://drive.google.com/drive/folders/1X5M_-aNIXFfKZDlP6e5PugvQUsf3M3Ia?usp=sharing
